name: Telegram Media Handler

on:
  push:
    branches:
      - main # Or your preferred branch
  workflow_dispatch: # To manually trigger the script

jobs:
  run-telegram-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Telegram Webhook Script
        run: node telegram_webhook.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add uploads/
          git commit -m "Add new media from Telegram" || echo "No changes to commit"
          git push


      on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes
